server:
  port: 8080

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.11:8761/eureka

jwt:
  secret:
    access: thisisjwtsecretkeyforgoraeonlinejudge20221218

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      httpclient:
        ssl:
          use-insecure-trust-manager: true
        connect-timeout: 2000
        response-timeout: 5s
      routes:
        - id: search
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**
        - id: judge
          uri: lb://JUDGE-SERVICE
          predicates:
            - Path=/judge/**
          filters:
            - AuthorizationHeaderFilter