apiVersion: v1
kind: Service
metadata:
  name: gorae-api-gateway-service
spec:
  selector:
    app: gorae-api-gateway
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gorae-api-gateway
  labels:
    app: gorae-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gorae-api-gateway
  template:
    metadata:
      labels:
        app: gorae-api-gateway
    spec:
      containers:
        - name: gorae-api-gateway
          image: lifetwoshot/gorae-api-gateway:latest
          imagePullPolicy: Always
